# photofield release configuration
#
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate -x
    - sh -c "cd ui && npm install && npm run build"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      # Unsupported by modernc sqlite currently
      - goos: windows
        goarch: "386"
    tags:
      - embedstatic
dockers:
  - dockerfile: Dockerfile-goreleaser
    image_templates:
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}"
      - "ghcr.io/smilyorg/photofield:v{{ .Major }}"
      - "ghcr.io/smilyorg/photofield:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/smilyorg/photofield:latest"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
