# photofield release configuration
#
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate -x
    - sh -c "cd docs && npm install && npm run docs:build && cd ../ui && npm install && npm run build"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      # Unsupported by modernc sqlite currently
      - goos: windows
        goarch: "386"
    tags:
      - embedui
      - embeddocs
      - embedgeo
dockers:
  - dockerfile: Dockerfile-goreleaser
    use: buildx
    image_templates:
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

  - dockerfile: Dockerfile-goreleaser
    use: buildx
    image_templates:
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/smilyorg/photofield:{{ .Tag }}"
    image_templates:
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-amd64"
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/smilyorg/photofield:v{{ .Major }}"
    image_templates:
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-amd64"
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-arm64"
      
  - name_template: "ghcr.io/smilyorg/photofield:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-amd64"
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-arm64"
      
  - name_template: "ghcr.io/smilyorg/photofield:latest"
    image_templates:
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-amd64"
      - "ghcr.io/smilyorg/photofield:{{ .Tag }}-arm64"

archives:  
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
