
collections:
  - name: Anniversary Trip
    list_limit: 100
    dirs:
      - /photo/Moments/2020 First Wedding Anniversary Trip

render:
  max_solid_pixel_area: 1000
    
layout:
  limit: 100
