FROM alpine:latest
RUN apk add --no-cache exiftool ffmpeg

ARG binary=photofield

WORKDIR /app
COPY $binary ./photofield

RUN mkdir ./data && touch ./data/configuration.yaml

EXPOSE 8080
ENV PHOTOFIELD_DATA_DIR=./data
ENTRYPOINT ["./photofield"]
