{
 "title": "Photofield",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cache",
    "query": "scene,image,image_info,path,geometry"
   },
   { "name": "indexer", "query": "metadata,contents" },
   { "name": "path", "query": { "query": "label_values(path)" } },
   { "name": "source", "query": { "query": "label_values(source)" } },
   { "name": "percentile", "label": "Latency p", "query": "50" }
  ]
 },
 "panels": [
  {
   "title": "Latency for $path",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(pf_http_latency_bucket{path=\"$path\"}[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Load Latency (p$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(pf_source_latency_bucket{source=~\"$source\"}[1m])) by (le, source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Load Latency / Original Megapixel (p$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(pf_source_per_original_megapixel_latency_bucket{source=~\"$source\"}[1m])) by (le, source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Load Latency / Resized Megapixel (p$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(pf_source_per_resized_megapixel_latency_bucket{source=~\"$source\"}[1m])) by (le, source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Load Latency Diff vs. Predicted (p$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(pf_source_latency_abs_diff_bucket{source=~\"$source\"}[1m])) by (le, source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Load Latency (p$percentile)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(histogram_quantile($percentile/100, sum(rate(pf_source_latency_bucket{source=~\"$source\"}[$__range])) by (le, source)))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Load Latency / Original Megapixel (p$percentile)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(histogram_quantile($percentile/100, sum(rate(pf_source_per_original_megapixel_latency_bucket{source=~\"$source\"}[$__range])) by (le, source)))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Load Latency / Resized Megapixel (p$percentile)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(histogram_quantile($percentile/100, sum(rate(pf_source_per_resized_megapixel_latency_bucket{source=~\"$source\"}[$__range])) by (le, source)))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Load Latency Diff vs. Predicted (p$percentile)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(histogram_quantile($percentile/100, sum(rate(pf_source_latency_abs_diff_bucket{source=~\"$source\"}[$__range])) by (le, source)))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Source Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
   "repeat": "source",
   "options": { "content": "# ${source}" },
   "targets": [
    {
     "expr": "sum by(le) (rate(pf_source_latency_bucket{source=~\"$source\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$source - Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "repeat": "source",
   "targets": [
    {
     "expr": "sum by(le) (rate(pf_source_latency_bucket{source=~\"$source\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$source - Latency / Original MP",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "repeat": "source",
   "targets": [
    {
     "expr": "sum by(le) (rate(pf_source_per_original_megapixel_latency_bucket{source=~\"$source\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$source - Latency / Resized MP",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 42 },
   "repeat": "source",
   "targets": [
    {
     "expr": "sum by(le) (rate(pf_source_per_resized_megapixel_latency_bucket{source=~\"$source\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$source - Latency Diff vs. Predicted",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 49 },
   "repeat": "source",
   "targets": [
    {
     "expr": "sum by(le) (rate(pf_source_latency_abs_diff_bucket{source=~\"$source\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"pf_index_${indexer}_pending\"}, \"name\", \"$1\", \"__name__\", \"pf_index_(.*)_pending\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Metadata Indexing Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pf_index_metadata_done[10s])"
    }
   ]
  },
  {
   "title": "Contents Indexing Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pf_index_contents_done[10s])"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[2s])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "heap" }
   ]
  },
  {
   "title": "Memory Allocation Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[10s])",
     "legendFormat": "mallocs"
    },
    {
     "expr": "rate(go_memstats_frees_total[10s])",
     "legendFormat": "frees"
    }
   ]
  },
  {
   "title": "Multithreading",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "goroutines" },
    { "expr": "go_threads", "legendFormat": "threads" }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=~\"0.75|1\"}",
     "legendFormat": "{{quantile}} quantile"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"pf_${cache}_cache_ratio\"}, \"name\", \"$1\", \"__name__\", \"pf_(.*)_cache_ratio\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"pf_${cache}_cache_cost_active\"}, \"name\", \"$1\", \"__name__\", \"pf_(.*)_cache_cost_active\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$cache cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "repeat": "cache",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "pf_${cache}_cache_ratio", "legendFormat": "hit ratio" },
      { "expr": "pf_${cache}_cache_cost_active", "legendFormat": "size" }
     ]
    },
    {
     "title": "Sets / Gets",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "rate(pf_${cache}_cache_sets_dropped[1m])",
       "legendFormat": "sets dropped"
      },
      {
       "expr": "rate(pf_${cache}_cache_sets_rejected[1m])",
       "legendFormat": "sets rejected"
      },
      {
       "expr": "rate(pf_${cache}_cache_gets_dropped[1m])",
       "legendFormat": "gets dropped"
      },
      {
       "expr": "rate(pf_${cache}_cache_gets_kept[1m])",
       "legendFormat": "gets kept"
      }
     ]
    },
    {
     "title": "Keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "rate(pf_${cache}_cache_keys_added[1m])",
       "legendFormat": "added"
      },
      {
       "expr": "-rate(pf_${cache}_cache_keys_evicted[1m])",
       "legendFormat": "evicted"
      },
      {
       "expr": "rate(pf_${cache}_cache_keys_updated[1m])",
       "legendFormat": "updated"
      }
     ]
    },
    {
     "title": "Cost",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(pf_${cache}_cache_cost_added[1m])",
       "legendFormat": "added"
      },
      {
       "expr": "-rate(pf_${cache}_cache_cost_evicted[1m])",
       "legendFormat": "evicted"
      }
     ]
    }
   ]
  }
 ]
}