apiVersion: 1
datasources:
- orgId: 1
  version: 5
  name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  jsonData:
    httpMethod: POST
    queryTimeout: ""
    timeInterval: 1s
