name: release

on:
  push:
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Check dependencies & generated files
        run: task check

      - name: Build/download dependencies
        run: task deps

      - name: Build one platform
        run: |
          GOOS=linux GOARCH=amd64 OUTPUT=./photofield task build:binary
          ./photofield -version
          rm ./photofield

      - name: Build & package all platforms
        run: |
          task archive:all checksums

