name: unit-tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Check dependencies & generated files
        run: task check

      - name: Build/download dependencies
        run: task deps

      - name: Install test dependencies
        run: |
          # Exclude documentation files to reduce image size
          # See https://github.com/actions/runner-images/issues/10977
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF
          sudo apt-get update
          sudo apt-get install -y exiftool ffmpeg libjpeg-turbo-progs

      - name: Run unit tests
        run: task test
